function [ERSP, timesout, freqsout] = doERSP(EEG, data, params)

[~,ERSP,ITC,~,timesout, freqsout, erspboot] = evalc(['newtimef(data,' ...
    'size(EEG.data,2), ' ...
    'params.ersplimits, ' ...
    '256, ' ...              % sampling rate
    '[3         0.5], ' ... % cycles (starting from 3 minimum)
    '''elocs'', EEG.chanlocs, ' ...
    '''chaninfo'', EEG.chaninfo, ' ...
    '''alpha'',0.01, '...
    '''freqs'', [7 40], ' ... % frequency range
    '''nfreqs'', 64, ' ...
    '''plotphase'', ''off'', ' ...
    '''plotersp'', ''off'', ' ...
    '''plotitc'', ''off'', ' ...
    '''padratio'', 2, ' ...
    '''baseline'', params.powerbaseline, '...
    '''trialbase'', params.trialbase, ' ...
    '''verbose'', ''off'' );']);

end