
for s = [315 317 318 321 322]
    for act = [1 2];

% EEG = pop_loadset('filename',['control_' num2str(s) '_0.5-30flt_M1M2ref_MANrej_ICA_ICrm_evtEdited.set'],...
%     'filepath',['C:\\Users\\user\\Dropbox\\study 3 - CFS EEG\\' num2str(s)]);  
% if act == 1
% EEG = pop_epoch( EEG, {  '111' '112' '114' '124'  }, [-2.55           1.9], ... 
%     'newname', num2str(act), 'epochinfo', 'yes');
% else
%   EEG = pop_epoch( EEG, {  '121' '122' '123' '113'  }, [-2.55           1.9], ... 
%     'newname', num2str(act), 'epochinfo', 'yes'); 
% end
% EEG = eeg_checkset( EEG );
% EEG = pop_rmbase( EEG, [-2500          -2000]);
% EEG = eeg_checkset( EEG );
% 
% if act == 1
% EEG = pop_saveset( EEG, 'filename', [num2str(s) '_MF.set'],'filepath', ...
%    ['C:\Users\user\Dropbox\study 3 - CFS EEG\' num2str(s) '\control epochs'], ...
%    'savemode', 'onefile');
% else
%     EEG = pop_saveset( EEG, 'filename', [num2str(s) '_ML.set'],'filepath', ...
%    ['C:\Users\user\Dropbox\study 3 - CFS EEG\' num2str(s) '\control epochs'], ...
%    'savemode', 'onefile');
% end


if act == 1
EEG = pop_loadset('filename', [num2str(s) '_MF.set'],'filepath', ...
   ['C:\Users\user\Dropbox\study 3 - CFS EEG\' num2str(s) '\control epochs']);
else
    EEG = pop_loadset( 'filename', [num2str(s) '_ML.set'],'filepath', ...
   ['C:\Users\user\Dropbox\study 3 - CFS EEG\' num2str(s) '\control epochs']);
end

figure;
% [ERSP, ~,~, times, freqs] =  
pop_newtimef( EEG, ...
                1,13, ...
                [-2550 1850], ...
                [3         0.5] , ...
                'elocs', EEG.chanlocs, ...
                'chaninfo', EEG.chaninfo, ...
                'freqs', [3 30], ...
                'nfreqs', 60, ...
                'plotphase', 'off', ...
                'padratio', 2, ...
                'baseline',[-2550 -1900], ...
                'erspmax', 3, ...
                'verbose', 'off',...
                'title', [num2str(s) '_' num2str(act) '_']);

    end
end